# Generated by Django 2.2.5 on 2019-10-31 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20191005_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='journalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIdInt', models.IntegerField(default=None, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('journalEntry', models.CharField(max_length=2000)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.userModel')),
            ],
        ),
    ]
